services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env
    depends_on:
      - db
      - cache
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: waiting_room_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  cache:
    image: redis:7
    ports:
      - "6379:6379"
    env_file:
      - ./.env
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge