apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: waiting-room-api
spec:
  selector:
    app: waiting-room-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP